name: Pull Request events
run-name: ${{ github.actor }} pushed to PR
on:
  - pull_request
jobs:
  linters-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Style Check - Ruff
        run: |
          ruff check
      - name: Typing Check - MyPy
        run: |
          mypy --install-types
          mypy app --disallow-untyped-defs --warn-unreachable
